spring:
  application:
    name: eureka-client-demo
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
